#keep productdb ready in postgrSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
#for docker 

#spring.datasource.url=jdbc:localhost://postgre-container:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=Ritwik123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8080
spring.datasource.hikari.initializationFailTimeout=60000
